//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0_Hunger.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public admin()
        {
            this.employees = new HashSet<employee>();
            this.requests = new HashSet<request>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
